# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-12 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_cobweb', '0005_auto_20171012_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='os_kernel',
        ),
    ]
