# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-10-12 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_cobweb', '0006_remove_host_os_kernel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='exist',
            field=models.IntegerField(default=0, verbose_name=b'status'),
        ),
    ]
